// Relative path: /src/app/[locale]/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import LenisScroll from '@/components/LenisScroll';
import { CartProvider } from '@/context/CartContext';

// Load Neue Montreal font family as the global font
const neueMontrealFont = localFont({
  src: [
    {
      path: '../../../public/fonts/NeueMontreal-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/NeueMontreal-LightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../../../public/fonts/NeueMontreal-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/NeueMontreal-Italic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../../../public/fonts/NeueMontreal-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/NeueMontreal-MediumItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../../public/fonts/NeueMontreal-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/NeueMontreal-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-neue-montreal',
  display: 'swap',
  fallback: ['system-ui', '-apple-system', 'sans-serif'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={neueMontrealFont.variable} suppressHydrationWarning>
      <body className={neueMontrealFont.className} suppressHydrationWarning>
        <CartProvider>
          <LenisScroll />
          <Header />
          <div className="min-h-[calc(100vh)]">{children}</div>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}